In [3]:
import random
import numpy as np

In [4]:
a = [random.random() for i in range(20)]

In [5]:
print a

[0.7913390732471347, 0.3320991254725463, 0.6942542835561637, 0.5017376442120168, 0.9250853369181404, 0.9240313217696596, 0.02206174822664375, 0.31158360717556444, 0.6409402741662631, 0.8299383105487612, 0.7053750927310225, 0.18562244647647252, 0.6303375461807538, 0.0742608001002043, 0.15175558548730983, 0.3513845426283565, 0.8454496324299748, 0.7675469279774406, 0.7334704472091844, 0.9604686165278248]


<h3> Exploring the function of mask how we can put a list inside numpy array </h3>

In [6]:
mask = range(5)

In [7]:
a = np.array(a)

In [8]:
a[mask]

array([ 0.79133907,  0.33209913,  0.69425428,  0.50173764,  0.92508534])

<h3> Exploring 2d array </h3>

In [9]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
b[1,2]

7

In [12]:
b[1]

array([5, 6, 7, 8])

In [13]:
b[1,:]

array([5, 6, 7, 8])

In [14]:
b[:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
b[:,1]

array([2, 6])

In [16]:
b = np.array([1,2,3,4])

In [17]:
np.dot(b,b)

30

In [18]:
c = np.array([[1,2,3,4],[5,6,7,8]])

In [19]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
a = np.array([4,5,6,7])

In [21]:
c - a

array([[-3, -3, -3, -3],
       [ 1,  1,  1,  1]])

In [22]:
a * a

array([16, 25, 36, 49])

In [23]:
a.sum(axis = 0)

22

In [24]:
a

array([4, 5, 6, 7])

In [25]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
c.sum(axis = 0)

array([ 6,  8, 10, 12])

In [27]:
c.sum(axis = 1)

array([10, 26])

<h3> Finding the L2 or euclidean distance based on test and train data </h3>

In [28]:
train = np.array([[1,2,3,4],[5,6,7,8],[3,1,9,8]])

In [29]:
test = np.array([[1,2,3,4],[5,6,7,8],[1,1,1,1],[3,2,1,6]])

In [30]:
test.shape

(4L, 4L)

In [31]:
train.shape

(3L, 4L)

In [32]:
#and we have to make a vectorized operation so that 
#we can get 4 * 3 vector based on euclidean.Vectorized 
train.reshape(3,1,4)

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]],

       [[3, 1, 9, 8]]])

In [33]:
test.shape

(4L, 4L)

In [34]:
a = train.reshape(3,1,4) - test

In [35]:
a.shape

(3L, 4L, 4L)

In [36]:
b = a.sum(axis = 2)

In [37]:
b.shape

(3L, 4L)

In [38]:
b

array([[  0, -16,   6,  -2],
       [ 16,   0,  22,  14],
       [ 11,  -5,  17,   9]])

In [39]:
a

array([[[ 0,  0,  0,  0],
        [-4, -4, -4, -4],
        [ 0,  1,  2,  3],
        [-2,  0,  2, -2]],

       [[ 4,  4,  4,  4],
        [ 0,  0,  0,  0],
        [ 4,  5,  6,  7],
        [ 2,  4,  6,  2]],

       [[ 2, -1,  6,  4],
        [-2, -5,  2,  0],
        [ 2,  0,  8,  7],
        [ 0, -1,  8,  2]]])

In [40]:
a*a

array([[[ 0,  0,  0,  0],
        [16, 16, 16, 16],
        [ 0,  1,  4,  9],
        [ 4,  0,  4,  4]],

       [[16, 16, 16, 16],
        [ 0,  0,  0,  0],
        [16, 25, 36, 49],
        [ 4, 16, 36,  4]],

       [[ 4,  1, 36, 16],
        [ 4, 25,  4,  0],
        [ 4,  0, 64, 49],
        [ 0,  1, 64,  4]]])

In [41]:
(a*a).sum(axis = 2)

array([[  0,  64,  14,  12],
       [ 64,   0, 126,  60],
       [ 57,  33, 117,  69]])

In [42]:
b

array([[  0, -16,   6,  -2],
       [ 16,   0,  22,  14],
       [ 11,  -5,  17,   9]])

In [43]:
b.sum(axis = 1)

array([-12,  52,  32])

In [44]:
p = np.array([1,2,1,2,3,1,4,23])

In [45]:
np.bincount(p)

array([0, 3, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1], dtype=int64)

In [46]:
p.argmax()

7

In [47]:
#Array split

a = np.array(range(100))

In [48]:
p =np.array_split(a,6)

In [49]:
p

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]),
 array([34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]),
 array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]),
 array([68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83]),
 array([84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [50]:
p

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]),
 array([34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]),
 array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]),
 array([68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83]),
 array([84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]

In [51]:
np.hstack(p[:2]+p[4:])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [52]:
np.vstack(p[:2])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]])

In [53]:
a = np.array([[1,2,3,4],[4,5,6,7]])

In [54]:
(a**2).sum(axis = 1)

array([ 30, 126])

In [55]:
b

array([[  0, -16,   6,  -2],
       [ 16,   0,  22,  14],
       [ 11,  -5,  17,   9]])

In [56]:
b.sum(axis = 0)

array([ 27, -21,  45,  21])

In [57]:
b[0]

array([  0, -16,   6,  -2])

In [58]:
b[0,:]

array([  0, -16,   6,  -2])

In [59]:
a 

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [60]:
np.square(b[0] - a).sum(axis = 1)

array([370, 538])

In [62]:
a = np.array([[1,2,3,4,5],[6,6,7,8,8],[7,7,7,8,1]])

In [63]:
a

array([[1, 2, 3, 4, 5],
       [6, 6, 7, 8, 8],
       [7, 7, 7, 8, 1]])

In [68]:
a[np.arange(3),[1,2,3]].reshape(3,1)

array([[2],
       [7],
       [8]])

In [71]:
np.maximum(a,a)

array([[1, 2, 3, 4, 5],
       [6, 6, 7, 8, 8],
       [7, 7, 7, 8, 1]])

In [72]:
a = np.arange(100).reshape(5,20)

In [73]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
        97, 98, 99]])

In [75]:
b = np.random.choice(89)

In [76]:
b

67

In [79]:
a[1:3]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59]])

In [80]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
        57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
        77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
        97, 98, 99]])

In [82]:
np.argmax(a,axis = 1)

array([19, 19, 19, 19, 19], dtype=int64)

In [83]:
p = [1,2,3,4]
q = [5,6,7,8]
zip(p,q)

[(1, 5), (2, 6), (3, 7), (4, 8)]

In [86]:
a = np.array([1,2,3,4])

In [87]:
a.sum()

10

In [89]:
relu = lambda x : x*(x > 0)

In [90]:
relu(5)

5

In [91]:
relu(0)

0

In [92]:
relu(-1)

0

In [94]:
np.logspace(2,3,5)

array([  100.        ,   177.827941  ,   316.22776602,   562.34132519,
        1000.        ])

In [95]:
np.linspace(1,2,10)

array([ 1.        ,  1.11111111,  1.22222222,  1.33333333,  1.44444444,
        1.55555556,  1.66666667,  1.77777778,  1.88888889,  2.        ])